version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5433:5432"
    volumes:
      - postgres_test:/var/lib/postgresql/data

volumes:
  postgres_test:
