### FIND ALL

GET http://localhost:9001/ HTTP/1.1

### FIND ONE

GET http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff591 HTTP/1.1

### NOT FOUND

GET http://localhost:9001/cff442b9-d91a-4c41-b746-5d051c88c971 HTTP/1.1

### NOT ACCEPTABLE

GET http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff591 HTTP/1.1
accept: text/html

### UNSUPPORTED MEDIA TYPE

GET http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff591 HTTP/1.1
content-type: text/html

### CREATE

POST http://localhost:9001/ HTTP/1.1
content-type: application/json

{
  "title": "Get dry cleaning"
}

### BAD CREATE

POST http://localhost:9001/ HTTP/1.1
content-type: application/json

{
  "titles": "Get dry cleaning"
}

### UPDATE

PATCH http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff591 HTTP/1.1
content-type: application/json

{
  "title": "foo",
  "description": null,
  "completedAt": null
}

### BAD UPDATE

PATCH http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff591 HTTP/1.1
content-type: application/json

{
  "id": "abc",
  "titles": "foo",
  "description": null,
  "completedAt": null
}

### NOT FOUND UPDATE

PATCH http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff592 HTTP/1.1
content-type: application/json

{
  "title": "foo",
  "description": null,
  "completedAt": null
}

### REMOVE

DELETE  http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff591 HTTP/1.1
content-type: application/json

### NOT FOUND REMOVE

DELETE  http://localhost:9001/cf13b3f7-b7ae-4a1a-92f4-4a2c85aff592 HTTP/1.1
content-type: application/json
